### ISSUE TITLE
2.16.0 Release Breaking Changes if you relied on Vendored packages

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/requests#4069]
Hey so the 2.16.0 release broke all of the vendored things I am assuming. I have [issued](https://github.com/tomchristie/apistar/pull/189) two [PRs](https://github.com/encode/django-rest-framework/pull/5185) to two frameworks I use that rely on the vendored packages in requests.

The `changelog` was a bit obscure about this
> 2.16.0
> Unvendor ALL the things!

Something like `BREAKING CHANGE: Vendor packages have been removed, if you relied on these you will need to modify your code` would be nice in a 2.16.1 changelog update maybe?

I realize that it can be said these vendored packages are internal and should not be relied on but at least these packages had a use case for using requests and some of the underlying libs and used the vendor packages to ensure everything worked as expected with requests.

Anyone who was relying on these will have their code break upon upgrade, so perhaps a bigger version bump would have been welcome, but at least this can be a warning to people coming here wondering why stuff broke. My solution was a `compat.py` that conditionally imported `urllib3` (works the same for other vendored packages), see my PRs for that fix.

**Comment by Lukasa** [comment]
Yeah, I don't know why @kennethreitz released that: it was pretty obviously going to break a lot of software. Not sure what I can say here: this is ultimately @kennethreitz's software and he can do what he wants, and I'm not going to revert his changes. But there was simply no reason that unvendoring needed to be shipped prior to v3, so I really hope @kennethreitz reverts and pushes a release containing that revert.

**Comment by kennethreitz** [comment]
Related: #4073

**Comment by kennethreitz** [comment]
@audiolion can you provide a sample of the code you were importing to utilize the internal packaged code? I'd like to test that I'm brining back the namespace properly.

**Comment by kennethreitz** [comment]
2.16.1 released, which restores the `packages` namespace. Sorry for the hiccup!

**Comment by audiolion** [comment]
@kennethreitz hey! its the two PRs that I have in my first comment, you can check either for how I did it, worked for both of those libs

**Comment by johnthomas00** [comment]
Does not work for me, I may be doing it wrong.

```
(urlwatch) [jt@home bin]$ pip install requests==2.14.2
Requirement already satisfied: requests==2.14.2 in /home/jt/virtual/urlwatch/lib/python3.6/site-packages
(urlwatch) [jt@home bin]$ ./urlwatch 
(urlwatch) [jt@home bin]$ python
Python 3.6.1 (default, Apr  7 2017, 09:32:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> len(dir(requests.packages))
13
>>> exit()
(urlwatch) [jt@home bin]$ pip install requests==2.16.1
Collecting requests==2.16.1
  Using cached requests-2.16.1-py2.py3-none-any.whl
Requirement already satisfied: idna<2.6,>=2.5 in /home/jt/virtual/urlwatch/lib/python3.6/site-packages (from requests==2.16.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/jt/virtual/urlwatch/lib/python3.6/site-packages (from requests==2.16.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/jt/virtual/urlwatch/lib/python3.6/site-packages (from requests==2.16.1)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /home/jt/virtual/urlwatch/lib/python3.6/site-packages (from requests==2.16.1)
Installing collected packages: requests
  Found existing installation: requests 2.14.2
    Uninstalling requests-2.14.2:
      Successfully uninstalled requests-2.14.2
Successfully installed requests-2.16.1
(urlwatch) [jt@home bin]$ python
Python 3.6.1 (default, Apr  7 2017, 09:32:32) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> dir(requests)
['ConnectTimeout', 'ConnectionError', 'DependencyWarning', 'FileModeWarning', 'HTTPError', 'NullHandler', 'PreparedRequest', 'ReadTimeout', 'Request', 'RequestException', 'Response', 'Session', 'Timeout', 'TooManyRedirects', 'URLRequired', '__author__', '__author_email__', '__build__', '__builtins__', '__cached__', '__cake__', '__copyright__', '__description__', '__doc__', '__file__', '__license__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__title__', '__url__', '__version__', '_internal_utils', 'adapters', 'api', 'auth', 'certs', 'chardet', 'codes', 'compat', 'cookies', 'delete', 'exceptions', 'get', 'head', 'hooks', 'logging', 'major', 'minor', 'models', 'options', 'patch', 'post', 'put', 'request', 'session', 'sessions', 'status_codes', 'structures', 'urllib3', 'urllib3_version', 'utils', 'warnings']
```
Notice, no packages in the dir above.

**Comment by kennethreitz** [comment]
v2.16.2 of requests fixes the backwards incompatibility completely :)

**Comment by audiolion** [comment]
Sorry to ruin your Saturday! thanks for all you do

**Comment by kennethreitz** [comment]
No, sorry for ruining yours! :)

**Comment by thrawny** [comment]
This still does not work with 2.16.2.
```python
>>> import requests
>>> requests.packages
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'requests' has no attribute 'packages'
```

Was trying out the apistar project today and ran into this issue since it uses that way of accessing the module.

**Comment by kennethreitz** [comment]
ah, I can fix that.

**Comment by kennethreitz** [comment]
@thrawny v2.16.3 released, which restores this.

**Comment by kennethreitz** [comment]
Thanks for the report!
