### ISSUE TITLE
ImportError: cannot import name is_windows

### ISSUE THREAD

**Issue by papachoco** [kennethreitz/requests#2457]
I am not sure if this should be a bug for requests (2.5.2). httpie (http command) no longer works with requests 2.5.2. b/c the the method is_windows was removed from requests.compat

Traceback (most recent call last):
  File "/Users/csanchez/Projects/nti.dataserver-buildout/bin/http", line 413, in <module>
    import httpie.__main__
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/httpie-0.9.1-py2.7.egg/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/httpie-0.9.1-py2.7.egg/httpie/core.py", line 21, in <module>
    from httpie.compat import str, bytes, is_py3
  File "/Users/csanchez/Documents/workspace/nti.dataserver-buildout/eggs/httpie-0.9.1-py2.7.egg/httpie/compat.py", line 7, in <module>
    from requests.compat import is_windows, bytes, str, is_py3, is_py26
ImportError: cannot import name is_windows

**Comment by sigmavirus24** [comment]
This is a bug in httpie. We cleaned up old symbols we weren't using. `requests.compat` isn't a publicly documented or exported API.

**Comment by papachoco** [comment]
I figured ..
Thanks a lot

Carlos

**Comment by ahsentaqikazmi** [comment]
@papachoco  can you please share how you solved this error?

**Comment by nateprewitt** [comment]
@ahsentaqikazmi this is an issue with httpie rather than Requests. You should be able to find solutions in the related issue for that project (jakubroztocil/httpie#314).
